package dev.martinm.platform.notifications;

public enum NotificationType {
    SERVER_INVITATION,
    PROJECT_INVITATION,
    CONTACT_INVITATION,
    CONTACT_INVITATION_ACCEPTED,
    SERVER_INVITATION_ACCEPTED,
    CONTACT_REMOVED,
    PROJECT_INVITATION_ACCEPTED,
    SERVER_MEMBER_REMOVED,
    PROJECT_MEMBER_REMOVED,
    REQUEST_TO_JOIN,
    REQUEST_TO_JOIN_ACCEPTED
}
